#include "art.h"

/* Generated by scripts/pack-device-art.py — do not edit. */

extern const uint8_t human_cloth_img_start[] asm("_binary_human_cloth_img_start");
extern const uint8_t human_cloth_img_end[] asm("_binary_human_cloth_img_end");
static const lv_image_dsc_t dsc_human_cloth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 75,
        .h = 160,
        .stride = 150,
    },
    .data_size = 36000,
    .data = human_cloth_img_start,
};

extern const uint8_t human_leather_img_start[] asm("_binary_human_leather_img_start");
extern const uint8_t human_leather_img_end[] asm("_binary_human_leather_img_end");
static const lv_image_dsc_t dsc_human_leather = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 74,
        .h = 160,
        .stride = 148,
    },
    .data_size = 35520,
    .data = human_leather_img_start,
};

extern const uint8_t human_mail_img_start[] asm("_binary_human_mail_img_start");
extern const uint8_t human_mail_img_end[] asm("_binary_human_mail_img_end");
static const lv_image_dsc_t dsc_human_mail = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 76,
        .h = 160,
        .stride = 152,
    },
    .data_size = 36480,
    .data = human_mail_img_start,
};

extern const uint8_t human_plate_img_start[] asm("_binary_human_plate_img_start");
extern const uint8_t human_plate_img_end[] asm("_binary_human_plate_img_end");
static const lv_image_dsc_t dsc_human_plate = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 80,
        .h = 160,
        .stride = 160,
    },
    .data_size = 38400,
    .data = human_plate_img_start,
};

extern const uint8_t orc_cloth_img_start[] asm("_binary_orc_cloth_img_start");
extern const uint8_t orc_cloth_img_end[] asm("_binary_orc_cloth_img_end");
static const lv_image_dsc_t dsc_orc_cloth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 109,
        .h = 160,
        .stride = 218,
    },
    .data_size = 52320,
    .data = orc_cloth_img_start,
};

extern const uint8_t orc_leather_img_start[] asm("_binary_orc_leather_img_start");
extern const uint8_t orc_leather_img_end[] asm("_binary_orc_leather_img_end");
static const lv_image_dsc_t dsc_orc_leather = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 109,
        .h = 160,
        .stride = 218,
    },
    .data_size = 52320,
    .data = orc_leather_img_start,
};

extern const uint8_t orc_mail_img_start[] asm("_binary_orc_mail_img_start");
extern const uint8_t orc_mail_img_end[] asm("_binary_orc_mail_img_end");
static const lv_image_dsc_t dsc_orc_mail = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 116,
        .h = 160,
        .stride = 232,
    },
    .data_size = 55680,
    .data = orc_mail_img_start,
};

extern const uint8_t orc_plate_img_start[] asm("_binary_orc_plate_img_start");
extern const uint8_t orc_plate_img_end[] asm("_binary_orc_plate_img_end");
static const lv_image_dsc_t dsc_orc_plate = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 115,
        .h = 160,
        .stride = 230,
    },
    .data_size = 55200,
    .data = orc_plate_img_start,
};

extern const uint8_t elf_cloth_img_start[] asm("_binary_elf_cloth_img_start");
extern const uint8_t elf_cloth_img_end[] asm("_binary_elf_cloth_img_end");
static const lv_image_dsc_t dsc_elf_cloth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 73,
        .h = 160,
        .stride = 146,
    },
    .data_size = 35040,
    .data = elf_cloth_img_start,
};

extern const uint8_t elf_leather_img_start[] asm("_binary_elf_leather_img_start");
extern const uint8_t elf_leather_img_end[] asm("_binary_elf_leather_img_end");
static const lv_image_dsc_t dsc_elf_leather = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 87,
        .h = 160,
        .stride = 174,
    },
    .data_size = 41760,
    .data = elf_leather_img_start,
};

extern const uint8_t elf_mail_img_start[] asm("_binary_elf_mail_img_start");
extern const uint8_t elf_mail_img_end[] asm("_binary_elf_mail_img_end");
static const lv_image_dsc_t dsc_elf_mail = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 73,
        .h = 160,
        .stride = 146,
    },
    .data_size = 35040,
    .data = elf_mail_img_start,
};

extern const uint8_t elf_plate_img_start[] asm("_binary_elf_plate_img_start");
extern const uint8_t elf_plate_img_end[] asm("_binary_elf_plate_img_end");
static const lv_image_dsc_t dsc_elf_plate = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 76,
        .h = 160,
        .stride = 152,
    },
    .data_size = 36480,
    .data = elf_plate_img_start,
};

extern const uint8_t undead_cloth_img_start[] asm("_binary_undead_cloth_img_start");
extern const uint8_t undead_cloth_img_end[] asm("_binary_undead_cloth_img_end");
static const lv_image_dsc_t dsc_undead_cloth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 107,
        .h = 160,
        .stride = 214,
    },
    .data_size = 51360,
    .data = undead_cloth_img_start,
};

extern const uint8_t undead_leather_img_start[] asm("_binary_undead_leather_img_start");
extern const uint8_t undead_leather_img_end[] asm("_binary_undead_leather_img_end");
static const lv_image_dsc_t dsc_undead_leather = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 87,
        .h = 160,
        .stride = 174,
    },
    .data_size = 41760,
    .data = undead_leather_img_start,
};

extern const uint8_t undead_mail_img_start[] asm("_binary_undead_mail_img_start");
extern const uint8_t undead_mail_img_end[] asm("_binary_undead_mail_img_end");
static const lv_image_dsc_t dsc_undead_mail = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 90,
        .h = 160,
        .stride = 180,
    },
    .data_size = 43200,
    .data = undead_mail_img_start,
};

extern const uint8_t undead_plate_img_start[] asm("_binary_undead_plate_img_start");
extern const uint8_t undead_plate_img_end[] asm("_binary_undead_plate_img_end");
static const lv_image_dsc_t dsc_undead_plate = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 93,
        .h = 160,
        .stride = 186,
    },
    .data_size = 44640,
    .data = undead_plate_img_start,
};

extern const uint8_t wep_stick_img_start[] asm("_binary_wep_stick_img_start");
extern const uint8_t wep_stick_img_end[] asm("_binary_wep_stick_img_end");
static const lv_image_dsc_t dsc_wep_stick = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 28,
        .h = 110,
        .stride = 56,
    },
    .data_size = 9240,
    .data = wep_stick_img_start,
};

extern const uint8_t wep_hatchet_img_start[] asm("_binary_wep_hatchet_img_start");
extern const uint8_t wep_hatchet_img_end[] asm("_binary_wep_hatchet_img_end");
static const lv_image_dsc_t dsc_wep_hatchet = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 42,
        .h = 72,
        .stride = 84,
    },
    .data_size = 9072,
    .data = wep_hatchet_img_start,
};

extern const uint8_t wep_spear_img_start[] asm("_binary_wep_spear_img_start");
extern const uint8_t wep_spear_img_end[] asm("_binary_wep_spear_img_end");
static const lv_image_dsc_t dsc_wep_spear = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 19,
        .h = 120,
        .stride = 38,
    },
    .data_size = 6840,
    .data = wep_spear_img_start,
};

extern const uint8_t wep_blade_img_start[] asm("_binary_wep_blade_img_start");
extern const uint8_t wep_blade_img_end[] asm("_binary_wep_blade_img_end");
static const lv_image_dsc_t dsc_wep_blade = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 36,
        .h = 90,
        .stride = 72,
    },
    .data_size = 9720,
    .data = wep_blade_img_start,
};

extern const uint8_t helm_cap_img_start[] asm("_binary_helm_cap_img_start");
extern const uint8_t helm_cap_img_end[] asm("_binary_helm_cap_img_end");
static const lv_image_dsc_t dsc_helm_cap = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 45,
        .h = 40,
        .stride = 90,
    },
    .data_size = 5400,
    .data = helm_cap_img_start,
};

extern const uint8_t helm_coif_img_start[] asm("_binary_helm_coif_img_start");
extern const uint8_t helm_coif_img_end[] asm("_binary_helm_coif_img_end");
static const lv_image_dsc_t dsc_helm_coif = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 48,
        .h = 58,
        .stride = 96,
    },
    .data_size = 8352,
    .data = helm_coif_img_start,
};

extern const uint8_t helm_iron_img_start[] asm("_binary_helm_iron_img_start");
extern const uint8_t helm_iron_img_end[] asm("_binary_helm_iron_img_end");
static const lv_image_dsc_t dsc_helm_iron = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 53,
        .h = 52,
        .stride = 106,
    },
    .data_size = 8268,
    .data = helm_iron_img_start,
};

extern const uint8_t shield_round_img_start[] asm("_binary_shield_round_img_start");
extern const uint8_t shield_round_img_end[] asm("_binary_shield_round_img_end");
static const lv_image_dsc_t dsc_shield_round = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 48,
        .h = 48,
        .stride = 96,
    },
    .data_size = 6912,
    .data = shield_round_img_start,
};

extern const uint8_t shield_tower_img_start[] asm("_binary_shield_tower_img_start");
extern const uint8_t shield_tower_img_end[] asm("_binary_shield_tower_img_end");
static const lv_image_dsc_t dsc_shield_tower = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 43,
        .h = 64,
        .stride = 86,
    },
    .data_size = 8256,
    .data = shield_tower_img_start,
};

extern const uint8_t field_greenroad_img_start[] asm("_binary_field_greenroad_img_start");
extern const uint8_t field_greenroad_img_end[] asm("_binary_field_greenroad_img_end");
static const lv_image_dsc_t dsc_field_greenroad = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 233,
        .h = 233,
        .stride = 466,
    },
    .data_size = 108578,
    .data = field_greenroad_img_start,
};

extern const uint8_t field_ironpit_img_start[] asm("_binary_field_ironpit_img_start");
extern const uint8_t field_ironpit_img_end[] asm("_binary_field_ironpit_img_end");
static const lv_image_dsc_t dsc_field_ironpit = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 233,
        .h = 233,
        .stride = 466,
    },
    .data_size = 108578,
    .data = field_ironpit_img_start,
};

extern const uint8_t field_moonwood_img_start[] asm("_binary_field_moonwood_img_start");
extern const uint8_t field_moonwood_img_end[] asm("_binary_field_moonwood_img_end");
static const lv_image_dsc_t dsc_field_moonwood = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 233,
        .h = 233,
        .stride = 466,
    },
    .data_size = 108578,
    .data = field_moonwood_img_start,
};

extern const uint8_t field_barrow_img_start[] asm("_binary_field_barrow_img_start");
extern const uint8_t field_barrow_img_end[] asm("_binary_field_barrow_img_end");
static const lv_image_dsc_t dsc_field_barrow = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 233,
        .h = 233,
        .stride = 466,
    },
    .data_size = 108578,
    .data = field_barrow_img_start,
};

extern const uint8_t field_ashfen_img_start[] asm("_binary_field_ashfen_img_start");
extern const uint8_t field_ashfen_img_end[] asm("_binary_field_ashfen_img_end");
static const lv_image_dsc_t dsc_field_ashfen = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 233,
        .h = 233,
        .stride = 466,
    },
    .data_size = 108578,
    .data = field_ashfen_img_start,
};

extern const uint8_t enemy_img_start[] asm("_binary_enemy_img_start");
extern const uint8_t enemy_img_end[] asm("_binary_enemy_img_end");
static const lv_image_dsc_t dsc_enemy = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 88,
        .h = 100,
        .stride = 176,
    },
    .data_size = 26400,
    .data = enemy_img_start,
};

extern const uint8_t campfire_img_start[] asm("_binary_campfire_img_start");
extern const uint8_t campfire_img_end[] asm("_binary_campfire_img_end");
static const lv_image_dsc_t dsc_campfire = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 45,
        .h = 48,
        .stride = 90,
    },
    .data_size = 6480,
    .data = campfire_img_start,
};

extern const uint8_t mob_gnoll_img_start[] asm("_binary_mob_gnoll_img_start");
extern const uint8_t mob_gnoll_img_end[] asm("_binary_mob_gnoll_img_end");
static const lv_image_dsc_t dsc_mob_gnoll = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 88,
        .h = 100,
        .stride = 176,
    },
    .data_size = 26400,
    .data = mob_gnoll_img_start,
};

extern const uint8_t mob_boar_img_start[] asm("_binary_mob_boar_img_start");
extern const uint8_t mob_boar_img_end[] asm("_binary_mob_boar_img_end");
static const lv_image_dsc_t dsc_mob_boar = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 88,
        .h = 100,
        .stride = 176,
    },
    .data_size = 26400,
    .data = mob_boar_img_start,
};

extern const uint8_t mob_wight_img_start[] asm("_binary_mob_wight_img_start");
extern const uint8_t mob_wight_img_end[] asm("_binary_mob_wight_img_end");
static const lv_image_dsc_t dsc_mob_wight = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 92,
        .h = 100,
        .stride = 184,
    },
    .data_size = 27600,
    .data = mob_wight_img_start,
};

extern const uint8_t mob_moth_img_start[] asm("_binary_mob_moth_img_start");
extern const uint8_t mob_moth_img_end[] asm("_binary_mob_moth_img_end");
static const lv_image_dsc_t dsc_mob_moth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 100,
        .h = 100,
        .stride = 200,
    },
    .data_size = 30000,
    .data = mob_moth_img_start,
};

extern const uint8_t mob_pike_img_start[] asm("_binary_mob_pike_img_start");
extern const uint8_t mob_pike_img_end[] asm("_binary_mob_pike_img_end");
static const lv_image_dsc_t dsc_mob_pike = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 101,
        .h = 100,
        .stride = 202,
    },
    .data_size = 30300,
    .data = mob_pike_img_start,
};

extern const uint8_t mob_crow_img_start[] asm("_binary_mob_crow_img_start");
extern const uint8_t mob_crow_img_end[] asm("_binary_mob_crow_img_end");
static const lv_image_dsc_t dsc_mob_crow = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 108,
        .h = 100,
        .stride = 216,
    },
    .data_size = 32400,
    .data = mob_crow_img_start,
};

extern const uint8_t mob_mire_eel_img_start[] asm("_binary_mob_mire_eel_img_start");
extern const uint8_t mob_mire_eel_img_end[] asm("_binary_mob_mire_eel_img_end");
static const lv_image_dsc_t dsc_mob_mire_eel = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 89,
        .h = 100,
        .stride = 178,
    },
    .data_size = 26700,
    .data = mob_mire_eel_img_start,
};

extern const uint8_t mob_ash_rat_img_start[] asm("_binary_mob_ash_rat_img_start");
extern const uint8_t mob_ash_rat_img_end[] asm("_binary_mob_ash_rat_img_end");
static const lv_image_dsc_t dsc_mob_ash_rat = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 104,
        .h = 100,
        .stride = 208,
    },
    .data_size = 31200,
    .data = mob_ash_rat_img_start,
};

extern const uint8_t mob_wolf_img_start[] asm("_binary_mob_wolf_img_start");
extern const uint8_t mob_wolf_img_end[] asm("_binary_mob_wolf_img_end");
static const lv_image_dsc_t dsc_mob_wolf = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 85,
        .h = 100,
        .stride = 170,
    },
    .data_size = 25500,
    .data = mob_wolf_img_start,
};

extern const uint8_t mob_spider_img_start[] asm("_binary_mob_spider_img_start");
extern const uint8_t mob_spider_img_end[] asm("_binary_mob_spider_img_end");
static const lv_image_dsc_t dsc_mob_spider = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 104,
        .h = 100,
        .stride = 208,
    },
    .data_size = 31200,
    .data = mob_spider_img_start,
};

extern const uint8_t mob_ogre_img_start[] asm("_binary_mob_ogre_img_start");
extern const uint8_t mob_ogre_img_end[] asm("_binary_mob_ogre_img_end");
static const lv_image_dsc_t dsc_mob_ogre = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 98,
        .h = 100,
        .stride = 196,
    },
    .data_size = 29400,
    .data = mob_ogre_img_start,
};

extern const uint8_t mob_brigand_img_start[] asm("_binary_mob_brigand_img_start");
extern const uint8_t mob_brigand_img_end[] asm("_binary_mob_brigand_img_end");
static const lv_image_dsc_t dsc_mob_brigand = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 87,
        .h = 100,
        .stride = 174,
    },
    .data_size = 26100,
    .data = mob_brigand_img_start,
};

extern const uint8_t mob_wyrm_img_start[] asm("_binary_mob_wyrm_img_start");
extern const uint8_t mob_wyrm_img_end[] asm("_binary_mob_wyrm_img_end");
static const lv_image_dsc_t dsc_mob_wyrm = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 99,
        .h = 100,
        .stride = 198,
    },
    .data_size = 29700,
    .data = mob_wyrm_img_start,
};

extern const uint8_t mob_hag_img_start[] asm("_binary_mob_hag_img_start");
extern const uint8_t mob_hag_img_end[] asm("_binary_mob_hag_img_end");
static const lv_image_dsc_t dsc_mob_hag = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 77,
        .h = 100,
        .stride = 154,
    },
    .data_size = 23100,
    .data = mob_hag_img_start,
};

extern const uint8_t pet_toad_img_start[] asm("_binary_pet_toad_img_start");
extern const uint8_t pet_toad_img_end[] asm("_binary_pet_toad_img_end");
static const lv_image_dsc_t dsc_pet_toad = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 53,
        .h = 56,
        .stride = 106,
    },
    .data_size = 8904,
    .data = pet_toad_img_start,
};

extern const uint8_t pet_rat_img_start[] asm("_binary_pet_rat_img_start");
extern const uint8_t pet_rat_img_end[] asm("_binary_pet_rat_img_end");
static const lv_image_dsc_t dsc_pet_rat = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 54,
        .h = 56,
        .stride = 108,
    },
    .data_size = 9072,
    .data = pet_rat_img_start,
};

extern const uint8_t pet_moth_img_start[] asm("_binary_pet_moth_img_start");
extern const uint8_t pet_moth_img_end[] asm("_binary_pet_moth_img_end");
static const lv_image_dsc_t dsc_pet_moth = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 71,
        .h = 56,
        .stride = 142,
    },
    .data_size = 11928,
    .data = pet_moth_img_start,
};

extern const uint8_t pet_crow_img_start[] asm("_binary_pet_crow_img_start");
extern const uint8_t pet_crow_img_end[] asm("_binary_pet_crow_img_end");
static const lv_image_dsc_t dsc_pet_crow = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 64,
        .h = 56,
        .stride = 128,
    },
    .data_size = 10752,
    .data = pet_crow_img_start,
};

extern const uint8_t fx_slash_img_start[] asm("_binary_fx_slash_img_start");
extern const uint8_t fx_slash_img_end[] asm("_binary_fx_slash_img_end");
static const lv_image_dsc_t dsc_fx_slash = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 92,
        .h = 90,
        .stride = 184,
    },
    .data_size = 24840,
    .data = fx_slash_img_start,
};

extern const uint8_t fx_coins_img_start[] asm("_binary_fx_coins_img_start");
extern const uint8_t fx_coins_img_end[] asm("_binary_fx_coins_img_end");
static const lv_image_dsc_t dsc_fx_coins = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 61,
        .h = 80,
        .stride = 122,
    },
    .data_size = 14640,
    .data = fx_coins_img_start,
};

extern const uint8_t fx_spark_img_start[] asm("_binary_fx_spark_img_start");
extern const uint8_t fx_spark_img_end[] asm("_binary_fx_spark_img_end");
static const lv_image_dsc_t dsc_fx_spark = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 91,
        .h = 90,
        .stride = 182,
    },
    .data_size = 24570,
    .data = fx_spark_img_start,
};

extern const uint8_t fx_dust_img_start[] asm("_binary_fx_dust_img_start");
extern const uint8_t fx_dust_img_end[] asm("_binary_fx_dust_img_end");
static const lv_image_dsc_t dsc_fx_dust = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 76,
        .h = 70,
        .stride = 152,
    },
    .data_size = 15960,
    .data = fx_dust_img_start,
};

extern const uint8_t portal_void_img_start[] asm("_binary_portal_void_img_start");
extern const uint8_t portal_void_img_end[] asm("_binary_portal_void_img_end");
static const lv_image_dsc_t dsc_portal_void = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = 466,
        .h = 466,
        .stride = 932,
    },
    .data_size = 434312,
    .data = portal_void_img_start,
};

extern const uint8_t portal_ring_img_start[] asm("_binary_portal_ring_img_start");
extern const uint8_t portal_ring_img_end[] asm("_binary_portal_ring_img_end");
static const lv_image_dsc_t dsc_portal_ring = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .w = 466,
        .h = 466,
        .stride = 932,
    },
    .data_size = 651468,
    .data = portal_ring_img_start,
};

static const lv_image_dsc_t *const figures[TAMI_PEOPLE_COUNT][4] = {
    { &dsc_human_cloth, &dsc_human_leather, &dsc_human_mail, &dsc_human_plate },
    { &dsc_orc_cloth, &dsc_orc_leather, &dsc_orc_mail, &dsc_orc_plate },
    { &dsc_elf_cloth, &dsc_elf_leather, &dsc_elf_mail, &dsc_elf_plate },
    { &dsc_undead_cloth, &dsc_undead_leather, &dsc_undead_mail, &dsc_undead_plate },
};

static const lv_image_dsc_t *const fields[TAMI_FIELD_COUNT] = {
    &dsc_field_greenroad, &dsc_field_ironpit, &dsc_field_moonwood,
    &dsc_field_barrow, &dsc_field_ashfen,
};

static const lv_image_dsc_t *const pets[TAMI_PET_KIND_COUNT] = {
    &dsc_pet_toad, &dsc_pet_rat, &dsc_pet_moth, &dsc_pet_crow,
};

const lv_image_dsc_t *tami_art_figure(TamiPeople p, int tier) {
    if (p >= TAMI_PEOPLE_COUNT || tier < 0 || tier > 3) {
        return NULL;
    }
    return figures[p][tier];
}

const lv_image_dsc_t *tami_art_field(TamiField f) {
    if (f >= TAMI_FIELD_COUNT) {
        return NULL;
    }
    return fields[f];
}

const lv_image_dsc_t *tami_art_pet(TamiPetKind k) {
    if (k >= TAMI_PET_KIND_COUNT) {
        return NULL;
    }
    return pets[k];
}

static const lv_image_dsc_t *const mobs[TAMI_FAMILY_COUNT] = {
    &dsc_mob_gnoll, &dsc_mob_boar, &dsc_mob_wight, &dsc_mob_moth,
    &dsc_mob_pike, &dsc_mob_crow, &dsc_mob_mire_eel, &dsc_mob_ash_rat,
    &dsc_mob_wolf, &dsc_mob_spider, &dsc_mob_ogre, &dsc_mob_brigand,
    &dsc_mob_wyrm, &dsc_mob_hag,
};

const lv_image_dsc_t *tami_art_enemy(void) { return &dsc_enemy; }
const lv_image_dsc_t *tami_art_mob(uint8_t family) {
    if (family >= TAMI_FAMILY_COUNT) {
        return &dsc_enemy;
    }
    return mobs[family];
}
const lv_image_dsc_t *tami_art_campfire(void) { return &dsc_campfire; }
const lv_image_dsc_t *tami_art_fx_slash(void) { return &dsc_fx_slash; }
const lv_image_dsc_t *tami_art_fx_coins(void) { return &dsc_fx_coins; }
const lv_image_dsc_t *tami_art_fx_spark(void) { return &dsc_fx_spark; }
const lv_image_dsc_t *tami_art_fx_dust(void) { return &dsc_fx_dust; }
const lv_image_dsc_t *tami_art_portal_void(void) { return &dsc_portal_void; }
const lv_image_dsc_t *tami_art_portal_ring(void) { return &dsc_portal_ring; }

const lv_image_dsc_t *tami_art_weapon(uint8_t look) {
    switch (look) {
    case TAMI_LOOK_HATCHET:
    case TAMI_LOOK_PICK:
        return &dsc_wep_hatchet;
    case TAMI_LOOK_SPEAR:
    case TAMI_LOOK_POLE:
        return &dsc_wep_spear;
    case TAMI_LOOK_BLADE:
    case TAMI_LOOK_SHIV:
        return &dsc_wep_blade;
    default:
        return &dsc_wep_stick;
    }
}
const lv_image_dsc_t *tami_art_helm(uint8_t look) {
    if (look == TAMI_LOOK_CAP) {
        return &dsc_helm_cap;
    }
    if (look == TAMI_LOOK_COIF) {
        return &dsc_helm_coif;
    }
    return &dsc_helm_iron;
}
const lv_image_dsc_t *tami_art_shield(uint8_t look) {
    if (look == TAMI_LOOK_SHIELD_TOWER) {
        return &dsc_shield_tower;
    }
    return &dsc_shield_round;
}
